name: "Tranzport"
services:
  postgres:
    image: 'postgres:16.9-alpine3.22'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

